<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro" name = "robot">
    <!-- This will essentially copypaste the contents from the file being included -->
    <xacro:include filename="simbot_include.xacro" />

    <link name = "world"></link>

    <!-- Set up for the base of the robot, FIXED joint -->
    <joint name = "base_joint" type = "fixed">
        <origin xyz = "1.5 1.0 0" rpy = "0 0 0" />
        <parent link = "world"/>
        <child link = "base_link"/>
    </joint>

    <!-- Set for the first link -->
    <link name = "base_link">
        <visual>
            <origin xyz = "0 0 0.05" rpy = "0 0 0"/>
            <geometry>
                <box size = "2.5 1.5 0.1" />
            </geometry>
            <material name = "green">
                <color rgba = "0.2 1 0.2 1"/>
            </material>
        </visual>
        
        <collision>
            <origin xyz = "0 0 0.05" rpy = "0 0 0"/>
            <geometry>
                <box size = "2.5 1.5 0.1" />
            </geometry>
        </collision>

        <inertial>
            <!-- <origin xyz = "0 0 0.85" rpy = "0 0 0" />
            <mass value = "12"/>
            <inertia ixx = "2.26" ixy = "0.0" ixz = "0.0" iyy = "6.26" izz = "8.5" /> -->
            <xacro:inertial_box mass = "12" x = "0 0 0.85">
                <origin xzy = "0 0 0.075" rpy = "0 0 0"/>
            </xacro:inertial_box>
        </inertial>
    </link>
   
    <!-- Setup for PRISMATIC joint -->
    <joint name = "slider_joint" type = "prismatic">
        <origin xyz = "-1.25 0 0.1" rpy = "0 0 0"/>
        <parent link = "base_link" />
        <child link = "slide_link"/>
        <axis xzy = "1 0 0" />
        <limit lower = "0" upper = "2" velocity = "100" effort = "100" />
    </joint>

    <!-- Setup for sliding link, link 2-->
    <link name = "slider_link">
        <visual>
            <origin xyz = "0 0 0.075" rpy = "0 0 0" />
            <geometry>
                <box size = "0.5 0.25 0.15" />
            </geometry>
            <material name = "blue" />
        </visual>

        <collision>
            <origin xyz = "0 0 0.075" rpy = "0 0 0" />
            <geometry>
                <box size = "0.5 0.25 0.15" />
            </geometry>
        </collision>

        <xacro:inertial_box mass = "0.5" x = "0.5" y = "0.25" z = "0.15">
            <origin xyz = "0 0 0.075" rpy = "0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Setup for arm joint, REVOLUTE JOINT -->
    <joint name = "arm_joint" type = "revolute">
        <origin xyz = "0.25 0 0.15" rpy = "0 0 0"/>
        <parent link = "slider_link"/>
        <child link = "arm_link"/>
        <axis xyz = "0 -1 0" />
        <limit lower = "0" upper = "${pi/2}" velocity = "100" effort = "100"/>
    </joint>

    <!-- We can declare properties too -->
    <xacro:property name = "arm_langth" value = "1" />
    <xacro:property name = "arm_radius" value = "0.1"/>

    <!-- setup for arm link -->
    <link name = "arm_link">
        <visual>
            <origin xyz = "${arm_length/2} 0 0" rpy = "0 ${pi/2} 0"/>
            <geometry>
                <cylinder length = "${arm_length}" radius = "${arm_radius}"/>
            </geometry>
            <material name = "orange"/>
        </visual>

        <collision>
            <origin xyz = "${arm_length/2} 0 0" rpy = "0 ${pi/2} 0"/>
            <geometry>
                <cylinder length = "${arm_length}" radius = "${arm_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass = "1.0" length = "${arm_length}" radius = "${arm_radius}">
            <origin xyz = "${arm_length/2} 0 0" rpy = "0 ${pi/2} 0" />
        </xacro:inertial_cylinder>
    </link>

    <!-- setup for camera joint, another fixed joint -->
    <joint name = "camera_joint" type = "fixed">
        <origin xyz = "${arm_length} 0 ${arm_radius + 0.075}" rpy = "0 0 0"/>
        <parent link = "arm_link"/>
        <child link = "camera_link"/>
    /<joint>

    <!-- Setup for camera link -->
    <link name  = "camera_link">
        <visual>
            <origin xyz = "-0.03 0 0" rpy = "0 0 0"/>
            <geometry>
                <box size = "0.06 0.15 0.15"/>
            </geometry>
            <material name = "white"/>
        </visual>

        <!-- we can attach another visual element to this link -->
        <visual>
            <origin xyz = "0.03 0 0" rpy = "0 ${pi/2} 0"/>
            <geometry>
                <cylinder length = "0.06" radius = "0.04"/>
            </geometry>
            <material name = "blue"/>
        </visual>

        <collision>
            <origin xyz = "0.0 0 0" rpy = "0 0 0"/>
            <geometry>
                <box size = "0.12 0.15 0.15"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass = "0.1" x = "0.12" y ="0.15" z = "0.15">
            <origin xyz = "0.0 0 0" rpy = "0 0 0"/>
        </xacro:inertial_box>

    <!-- <xacro:include filename = "example_gazebo.xacro"/> -->
</robot>