<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="car">
    
    <!-- This will be the file we use to simulate the 3-wheeled car in-class -->
    <xacro:include filename="simbot_include.xacro"/>

    <xacro:property name="chasis_x" value="0.10"/>
    <xacro:property name="chasis_y" value="0.25"/>
    <xacro:property name="chasis_z" value="0.07"/>

    <xacro:property name="wheel_diameter" value="0.07"/>
    <xacro:property name="wheel_width" value="0.03"/>
    <xacro:property name="front_wheel_diameter" value="0.035"/>


    <!-- Chasis of the robot -->
    <link name="chasis_link">
        <visual>
            <origin xyz="0 0 ${chasis_z/2 + wheel_diameter/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chasis_x} ${chasis_y} ${chasis_z}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${chasis_z/2 + wheel_diameter/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chasis_x} ${chasis_y} ${chasis_z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="1000" x="${chasis_x}" y="${chasis_y}" z="${chasis_z}">
                <origin xyz="0 0 ${chasis_z/2 + wheel_diameter/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
        
    </link>

    <!-- Joint for Back right wheel -->
    <joint name="wheel_br_joint" type="continuous">
        <parent link="chasis_link"/>
        <child link="wheel_br_link"/>
        <origin xyz="${chasis_x/2 + wheel_width/2} ${-(chasis_x - wheel_width/2)} ${chasis_z/2}" rpy="0 ${pi/2} 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <!-- Back Right wheel link -->
    <link name="wheel_br_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="80" length="${wheel_width}" radius="${wheel_diameter}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Joint for back left wheel -->
    <joint name="wheel_bl_joint" type="continuous">
        <parent link="chasis_link"/>
        <child link="wheel_bl_link"/>
        <origin xyz="${-(chasis_x/2 + wheel_width/2)} ${-(chasis_x - wheel_width/2)} ${chasis_z/2}" rpy="0 ${-pi/2} 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Front Back wheel link -->
    <link name="wheel_bl_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="80" length="${wheel_width}" radius="${wheel_diameter}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <!-- Joint for Front Wheel-->
    <joint name="wheel_front_joint" type="fixed">
        <origin xyz="0 ${chasis_y/3} 0"/>
        <parent link="chasis_link"/>
        <child link="wheel_front_link"/>
    </joint>

    <!-- Link for front wheel -->
    <link name="wheel_front_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${front_wheel_diameter}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${front_wheel_diameter}"/>
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="30" radius="${front_wheel_diameter}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
</robot>